kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding
  namespace: team-a
subjects:
# Google Group
- kind: Group
  name: team-a@example.com
- kind: Group
  name: team-b@example.com
- kind: Group
  name: team-c@example.com
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io