kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding
  namespace: team-a
subjects:
# Google Group
- kind: Group
  name: team-a@manishjindal.joonix.net
- kind: Group
  name: team-b@manishjindal.joonix.net
- kind: Group
  name: team-c@manishjindal.joonix.net
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io