apiVersion: v1
kind: LimitRange
metadata:
  name: tenant-a-limitrange
  namespace: team-a
spec:
  limits:
  - default:
      cpu: 500m
      memory: 750Mi
    defaultRequest:
      cpu: 250m
      memory: 400Mi
    type: container

