apiVersion: v1
kind: ResourceQuota
metadata:
  name: tenant-a-quota
  namespace: team-a
spec:
  hard:
    request.cpu: "1"
    request.memory: 1Gi
    limit.cpu: "2"
    limit.memory: 2Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: tenant-a-limitrange
spec:
  limits:
  - default:
      cpu: 500m
      memory: 750Mi
    defaultRequest:
      cpu: 250m
      memory: 400Mi
    type: container

